python3 evaluate.py --model "swin-b" --frame-rates 30 --dmap_type "threshold"
# python3 evaluate.py --model "vitdet-b" --frame-rates 100 --dmap_type "topk"
# python3 evaluate.py --model "vitdet-l" --frame-rates 100 --dmap_type "threshold"
# python3 evaluate.py --model "vitdet-l" --frame-rates 100 --dmap_type "topk"
# python3 evaluate.py --model "vitdet-h" --frame-rates 100 --dmap_type "threshold"
# python3 evaluate.py --model "vitdet-h" --frame-rates 100 --dmap_type "topk"
# python3 evaluate.py --model "vitdet-b" --frame-rates 30 --dmap_type "threshold"
# python3 evaluate.py --model "vitdet-b" --frame-rates 30 --dmap_type "topk"
# python3 evaluate.py --model "vitdet-l" --frame-rates 30 --dmap_type "threshold"
# python3 evaluate.py --model "vitdet-l" --frame-rates 30 --dmap_type "topk"
# python3 evaluate.py --model "vitdet-h" --frame-rates 30 --dmap_type "threshold"
# python3 evaluate.py --model "vitdet-h" --frame-rates 30 --dmap_type "topk"